In [4]:
# import neccasary libraries for file handeling
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import csv
from pathlib import Path
from math import log

## File Handling

In [ ]:
DATA_DIR = Path("../data")
DATA_DIR.mkdir(exist.ok=True)

In [13]:
# writing on Arden.txt in my DATA_DIR
Arden_file = DATA_DIR/ "Arden.txt"
with open(Arden_file, 'w') as file:
    file.write('Hello, my name is Arden \n It is Berlin campus \n We are studing Data Science.')

In [15]:
# Opening file with read mode 
# read mode 'r', the file must already exist 
with open (Arden_file, 'r') as file:
    print(file.read())
    for line in file:
        print(file.read())

Hello, my name is Arden
 It is Berlin campus
 We are studing Data Science.

In [17]:
# read fix number of characters
with open (Arden_file, 'r', encoding = "utf-8") as file:
    print(file.read(10))

Hello, my

In [18]:
# Sequential reads from the current cursor position
with open (Arden_file, 'r') as file:
    con = file.read(4)
    con1 = file.read(10)
    con2 = file.read()

print(con) # read first chunk
print(con1) # read second chunk
print(con2) # read third chunk

Hell
o, my name
 is Arden
 It is Berlin campus
 We are studing Data Science.

In [19]:
with open(Arden_file, 'a') as file:
    file.write('Hello, my name is Arden \n It is Berlin campus \n We are studing Data Science.')

In [21]:
# Spliting line into words
with open(Arden_file, 'r') as file:
    for line in file:
        # split each line into words      
        words = line.split()
        for word in words:
            print(f'{word.lower()}\t1')

hello,	1
my	1
name	1
is	1
arden	1
it	1
is	1
berlin	1
campus	1
we	1
are	1
studing	1
data	1
science.hello,	1
my	1
name	1
is	1
arden	1
it	1
is	1
berlin	1
campus	1
we	1
are	1
studing	1
data	1
science.	1

In [26]:
# removing unwanted spaces with strip() lstrip() and rstrip()
e = "    Hello, my name is Arden     "
print("Original:", repr(e))
print("Left stripped:", repr(e.lstrip()))
print("Right stripped:", repr(e.rstrip()))
print("Both sides stripped:", repr(e.strip()))

Original: '    Hello, my name is Arden     '
Left stripped: 'Hello, my name is Arden     '
Right stripped: '    Hello, my name is Arden'
Both sides stripped: 'Hello, my name is Arden'

In [ ]:
# Options for reading file
# r+: read and write . creating is not the option. Delete is not the optio. writing position is the begining of my file
# w+: write and read. creating is the option. Delete is the option. writing position is the begining of my file
# a+: append and read. creating is the option. Delete is not the option. writing position is the end of my file

In [29]:
# import a txt file
df = pd.read_csv("../data/Iris.csv", sep= ",")
# print(df)
# reading the head of file 
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [31]:
# imprt excel files
df = pd.read_excel("../data/DataStar.xlsx")
df.head()

           Date Store Location Food Department  Total Value (000's)
0           NaN            NaN             NaN                  NaN
1  1st Sep 1994  Wolverhampton            Meat                234.0
2  2nd Sep 1994        Grimsby           Baked                143.0
3  3rd Sep 1994         Durham   Confectionary                482.0
4  4th Sep 1994        Swansea          Floral                471.0

## Numpy Array creation

In [ ]:
# creating a a numpy array
arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print(type(arr))
# dimensions
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

<class 'numpy.ndarray'>
2
(2, 5)
10
int64

In [47]:
arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]], dtype = "float64")
print(arr)
print(arr[0][0])

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]
1.0

In [ ]:
tup = np.array((1, 2, 3, 4, 5))
print(type(tup))

<class 'numpy.ndarray'>

In [48]:
# create an array filled by zero
arr1 = np.zeros((3, 4))
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
# an array with fileed by 6
arr2 = np.full((3, 4), 6, dtype = "complex")
arr2

array([[6.+0.j, 6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j, 6.+0.j]])

In [52]:
# a sequence  with arrange()
arr3 = np.arange(0, 21, 5) # start:stop:step
arr3

array([ 0,  5, 10, 15, 20])

In [54]:
# creating sequence with linespace()
g = np.linspace(0, 21, 5) # start:stop:number of elements
g

array([ 0.  ,  5.25, 10.5 , 15.75, 21.  ])

In [56]:
# reshaping a 3 by 4 to 2 by 2 by 3
arr5 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
newarr = arr5.reshape(2, 2, 3)
newarr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [57]:
# flattening 2 dim array to 1 dim
arr6 = np.array([[1, 2, 3], [4, 5, 6]])
flattened = arr6.flatten()
flattened

array([1, 2, 3, 4, 5, 6])

## NUMPY INDEXING

In [62]:
#array slicing
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [65]:
s_arr = arr[::2, ::2]
s_arr

array([[ 1,  3],
       [ 9, 11]])

## Basic numpy operations

In [68]:
# arraay a and b
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
# add 1 to every elements
print(a+1)
print(b-2)
print(a.sum())

[[2 3]
 [4 5]]
[[3 4]
 [5 6]]
10

In [74]:
# adding element wise a and b
c = np.add(a, b)
d = np.subtract(a, b)
print(c)
print(d)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]

In [ ]:
# multply a and b
Mul_ab = np.multiply(a, b)
Mul_ab
# np.divide() is for dividing
# np.power(a, 2) is for power of a
# np.mod(a, b) is for remainder

array([[ 5, 12],
       [21, 32]])

In [80]:
# dot product a and b to get a scalar
dot_ab = np.vdot(a, b)
print(dot_ab)

70

In [81]:
# dot product a and b to get a scalar
dot_ab1 = np.dot(a, b)
print(dot_ab1)

[[19 22]
 [43 50]]

In [82]:
# Quetient and reminer 
np.divmod(a,b)

(array([[0, 0],
        [0, 0]]),
 array([[1, 2],
        [3, 4]]))

In [85]:
# logarityhm with base n
nplog = np.frompyfunc(log,2,1)
print(nplog(100,15))

1.7005483074552052

In [88]:
print(np.log2(a))
print(np.log10(b))

[[0.        1.       ]
 [1.5849625 2.       ]]
[[0.69897    0.77815125]
 [0.84509804 0.90308999]]